# Generated by Django 5.2 on 2025-04-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrinal_pa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrinal_pa.client')),
            ],
        ),
        migrations.CreateModel(
            name='SellerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrinal_pa.seller')),
            ],
        ),
    ]
