# Generated by Django 5.2 on 2025-05-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrinal_pa', '0003_order_date_update_order_order_date_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='rol',
            field=models.CharField(default='TODO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cant_product',
            field=models.JSONField(),
        ),
    ]
